remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
title: eZ80 for RC2014™ and compatible backplanes
description: An eZ80 CPU Module that works within the RC2014™ ecosystem
author: Dean Netherton
relative_links:
  enabled: true
  collections: false
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
